### ISSUE TITLE
HDL Writer prints empty port map if all ports are unconnected

### ISSUE THREAD

**Issue by swallat** [emsec/hal#125]
**Describe the bug**
When we add a gate to HAL and don't connect its pins HAL writes an invalid netlist with an empty port map.

**Expected behavior**
Either write `UNCONNECTED` as the assigned net or stop the writing altogether.

**Additional context**
Can occur in combination with #124

**Comment by devhoffmann** [comment]
AFAIK only output pins can be unconnected (we should do that) but input pins must have a net assigned.
In that case the writer should throw an error
