### ISSUE TITLE
Remove operator<< in gate.cpp and net.cpp?

### ISSUE THREAD

**Issue by FabianAlbertRub** [emsec/hal#135]
In src/netlist/gate.cpp and src/netlist/net.cpp we have still the `operator<<` function. Since you can't reach them from other files (there is no declaration in the header), I would suggest to remove them. What do you think?

**Comment by swallat** [comment]
@devhomann Can we remove this, or do we need it somewhere?

**Comment by devhoffmann** [comment]
Closed in HAL 2.0
