### ISSUE TITLE
Python editor should not open the same file in multiple tabs

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#140]
**Describe the bug**
In the Python editor, multiple tabs can be opened with the same file. This causes a similar issue as #139 because the editor does not synchronize those tabs. If you change something in one tab and save, then the other tab will not reflect this change. The user can thus easily overwrite their own file by accidentally opening it twice and forgetting which tab they worked in.

**To Reproduce**
1. Open a file in the Python editor.
2. Try to open the same file again.
3. See that you now have two tabs with the same file.

**Expected behavior**
There should never be more than one tab per file, meaning the editor should reject a request to open a file twice.

**Comment by devhoffmann** [comment]
pull request #155
