### ISSUE TITLE
Multi-selection in Python editor file chooser

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#141]
**Is your feature request related to a problem? Please describe.**
Opening more than one file in the Python editor can be tedious because the file chooser dialog must be used for each file separately. The file chooser also does not remember the last location, meaning the user must navigate to their files every time.

**Describe the solution you'd like**
The file chooser should allow selecting more than one Python script. If the user does this, one tab should open for each selected file.

**Describe alternatives you've considered**
It would also be nice if the file chooser remembered the last used folder.

**Comment by dertob** [comment]
Added in #158.
