### ISSUE TITLE
Add a save-all button in the Python editor

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#142]
**Is your feature request related to a problem? Please describe.**
For large projects, if you want to quit HAL you need to click all Python tabs separately to save their changes. If you need to restart HAL often, then this is annoying.

**Describe the solution you'd like**
I suggest adding a save-all button to the Python editor that simply saves all tabs with unsaved changes at once.

**Describe alternatives you've considered**
We should discuss how we handle tabs that are new scripts, i.e. that have never been saved. If the user does this excessively, this could result in a lot of file chooser dialogs opening. Maybe do this and cancel the whole process if the user cancels one of the file choosers?

**Comment by dertob** [comment]
Me and @ChuTriel are aware of this problem and we are actually already discussing how to implement this in a meaningful way. We definitely want to avoid the file chooser dialogs to open and the warnings for the python tabs when closing HAL. That's just annoying tbh. We were thinking about autosaving the contents of the python editor in a temp file after closing and reloading them on startup. Just like VS Code or Notepad++. I think that would be the most comfortable solution for the user.
