### ISSUE TITLE
Global content manager tracking is faulty

### ISSUE THREAD

**Issue by dertob** [emsec/hal#157]
**Describe the bug**
The global content manager doesn't track python tabs correctly. Depending on the position of the tab in the bar the script gets wrongly identified as saved or unsaved. This leads to wrong notifications popping up and eventual loss of data.

**To Reproduce**
1. Open 2 python script tabs in the editor e.g. 'a.py' and 'b.py'
2. Fill both tabs with some code and save both
3. Modify the content of 'a.py'
4. Move the tab 'a.py' to the right, thus switching the position with 'b.py' in the tab bar
5. Click on tab 'b.py' and save tab 'b.py'
6. Close HAL
7. HAL closes without warning, despite changes occurring in 'a.py'

**Expected behavior**
HAL should mark the correct script as modified and warn the user that the content of 'a.py' is modified.

**Additional context**
The way the changes are tracked in the content manager seem to be dependent on the index of the tab. This seems to be the main issue on first look.
I also see some problems using strings as an identifier and that that the functionality is implemented in the class where it is now. The name suggests placing it there, but I think 'content' was supposed to describe the widgets contained in the main window. Maybe we should discuss this?

**Comment by devhoffmann** [comment]
@dertob What is your status on this? Can you explain your solution strategy?

**Comment by dertob** [comment]
I think that the existing idea of a global class for tracking changes on files across all widgets is good and more elegant than trying to pass signals through multiple layers. My plan is to implement a new class with the same functionality provided in the current 'content manager'. To fix the issues we have with the current tracking I would equip each instance of the 'python_code_editor' with a uuid provided by Qt and safe that instead of just the file name or the tab number. Also one could argue to put the functionality from 'netlist_watcher' also in the new class. It's whole purpose is to track changes on the netlist.

My current plan is to implement this tomorrow.
