### ISSUE TITLE
Graph view does not update when moving one or more gates to an existing module

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#186]
**Describe the bug**
On branch integrate-new-graph-features, when right-clicking on a gate or a selection of gates, the user can move the gate(s) to a new or existing module. The latter does not update the view.

**To Reproduce**
1. open a netlist
2. create a module under the top module
2. in the graph view, enter the top module
3. right-click on a gate or a selection of gates
4. select "Move to module …" -> your created module
5. see that the change is not reflected in the graph view

**Expected behavior**
The graph view should update the way it does when you select "Move to module …" -> "New module …"

**Comment by swallat** [comment]
@RenWal How do you create the module? Via the python interface?

**Comment by RenWal** [comment]
You can do it that way. In my previous observation it does not make any difference whether you create the module via Python or the GUI.

```python
netlist.create_module("foo", netlist.get_top_module())
```

**Comment by RenWal** [comment]
Confirmed fixed in integrate-new-graph-features.
