### ISSUE TITLE
Possible typo in synopsys decorator

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#193]
This line in `gate_decorator_bdd_synopsys` seems incorrect:
https://github.com/emsec/hal/blob/25094f4e0d4befd52139851c8a164bd73d68bc9c/plugins/gate_libraries/src/gate_decorator_bdd_synopsys.cpp#L94
Both sides of the OR statement are equal.

@swallat since you introduced this piece of code in 09f820a9bc0227daa87c2bfe2dde270c49009847, could you please check if the right side of this statement should rather say `AOI22X2`?

**Comment by swallat** [comment]
@RenWal Actually the line was introduced by @devhoffmann before the transition to Github. @devhoffmann could you check that?

**Comment by devhoffmann** [comment]
Right literal should be `"AOI22X2"`, I will fix that
