### ISSUE TITLE
Keybind settings don't recognize "Command" on Mac

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#198]
**Describe the bug**
The keybind settings widget doesn't recognize the Command key on MacOS, so no keybinds with this key can be set up.

**Affects branch**
integrate-graph-features

**To Reproduce**
1. Go to the settings page
2. Select "Keyboard Shortcuts"
3. Attempt to set any keybind that contains the Command key
4. Nothing happens

**Expected behavior**
The keybind should be visible in the settings widget and should then be applied when clicking OK.

**Desktop:**
- MacOS only

**Comment by joern274** [comment]
Keyboard shortcuts with Command Key tested on Macmini both with PC and Magic Keyboard. Shortcut assignment works as expected, described problem cannot be reproduced.
