### ISSUE TITLE
Marked net is not continuously marked

### ISSUE THREAD

**Issue by nils1603** [emsec/hal#201]
**Describe the bug**
Marked net is not continuously marked

**Expected behavior**
Net should be continuously marked

<img width="611" alt="Screenshot 2019-11-14 at 21 20 53" src="https://user-images.githubusercontent.com/13201750/68893275-196d4f80-0725-11ea-9c72-5a30c77951ae.png">

**Comment by RenWal** [comment]
The underlying issue here is that nets are sometimes still rendered on top of each other.

**Comment by nils1603** [comment]
Yes, looks like. I just wanted to collect everything that I notice.
