### ISSUE TITLE
Make a comparison with Degate

### ISSUE THREAD

**Issue by XVilka** [emsec/hal#230]
There exist an alternative - [Degate](https://github.com/nitram2342/degate). Sadly, it's not actively maintained, but contained a lot of interesting ideas. It would be nice to have a comparison.

![image](https://user-images.githubusercontent.com/203261/71620781-bff2ae80-2c06-11ea-802e-cb31d33e5e30.png)

**Comment by swallat** [comment]
Thanks for the comment. In general, it might be a good idea to point out other projects, and explain where HAL fits in there.
