### ISSUE TITLE
Graph algorithms not yet compatible with multi-driven nets

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#255]
**Describe the bug**
The `graph_algorithm` plugin makes several references to `net::get_source()`, which is deprecated and superseded by `net::get_sources()`. This will break functionality if multi-driven nets are encountered in the netlist.

**Expected behavior**
The plugin should be fully compatible with multi-driven nets.

(Documenting this here since I believe we never talked about this internally)

**Comment by SJulianS** [comment]
will be fixed  #in #564
