### ISSUE TITLE
Importing hal_gui breaks graph shaders

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#261]
**Describe the bug**
After running `import hal_gui`, the gates in the graph lose their text and selection color. Nets lose their selection color and pins are no longer rendered.

**To Reproduce**
1. Open any netlist
2. Type `import hal_gui` or `from hal_gui import gui` into the Python console or the Python editor and execute
3. Click on any gate or module

**Expected behavior**
The shaders must not break.

**Screenshots**
![Bildschirmfoto von 2020-03-20 15-53-36](https://user-images.githubusercontent.com/10632547/77175502-08fa2680-6ac3-11ea-91ff-d5ded97fcab3.png)

**Comment by RenWal** [comment]
@dertob 
@Slowpoke42

**Comment by RenWal** [comment]
Turned out to be some dependency issue on my side, sorry

**Comment by nils1603** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [View Manager](https://trello.com/c/2RZjVQbB/11-view-manager)
