### ISSUE TITLE
Inconsistency: resolving pins from nets, resolving nets from ports

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#269]
**Is your feature request related to a problem? Please describe.**
We can get the fan in net from a gate, given a pin (but not the other way around). However, we can't get the net from a module, given a port (only the other way around). This is inconsistent.

**Describe the solution you'd like**
We should have a way to resolve pins<->nets and ports<->nets in both directions.

**Additional context**
Not having this makes me write search loops in the GUI code all over the place.

**Comment by SJulianS** [comment]
I've added the requested functionality in our developer branch.
