### ISSUE TITLE
Add support for pg_type nwell/pwell (context: for NanGate 15nm)

### ISSUE THREAD

**Issue by ichthys101** [emsec/hal#382]
Thanks for your work on this tool. It's very cool!

**Is your feature request related to a problem? Please describe.**
I tried to load the NanGate 15nm liberty file, but the parser doesn't like nwell/pwell types for pg_pin 

**Describe the solution you'd like**
Add support for these pin types. Are the pg_pins used for any type of analysis right now?

**Describe alternatives you've considered**
Maybe a workaround could just be to ignore such pins (if they aren't being used for any of the current plugins...)

**Additional context**
I tried using the NanGate_15nm_OCL_functional.lib file from [https://si2.org/open-cell-library/](https://si2.org/open-cell-library/)

**Comment by SJulianS** [comment]
Sorry for the late reply, I've just fixed the issue today and verified the fix with the respective liberty file. All pg_pins that HAL cannot deal with will continue to throw a warning, but the gate library will be parsed nonetheless and may subsequently be used within HAL. Thanks for the report!
