### ISSUE TITLE
ANSI/IEEE Std 91/91a-1991 Symbols for the gates

### ISSUE THREAD

**Issue by swallat** [emsec/hal#4]
From Christian Kison: 
The idea is to replace standard gates with their corresponding ANSI symbol.
E.g. https://de.wikipedia.org/wiki/Datei:Logic-gate-and-us.svg AND GATE
First of all this helps ASIC reversing. Secondly, this might turn out to be an good orientation-helper. Recognizing a place with like 5 XORS is easier, compared to seeing rectangles everywhere. (Its the same for the IDA graph view in software reversing.) Thirdly fastens reversing as "default" subcircuits are seen faster. No need to look for the type of every gate in the rectangle.

**Comment by SJulianS** [comment]
currently out of scope, might come back to it later
