### ISSUE TITLE
Python functions cannot access imports and global objects

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#46]
In this code snippet:

```python
import itertools
itertools
def test():
  itertools
test()
```

The call inside the function throws a NameError. The same holds for accessing global variables. That includes functions, meaning you can't access a function from within a function.

**Comment by swallat** [comment]
Do you call it via the python shell or the editor?

**Comment by RenWal** [comment]
This happens for me in both the shell and the editor:

```
NameError: name 'itertools' is not defined

At:
  <string>(5): test
  <string>(6): <module>
```

**Comment by RenWal** [comment]
This is a workaround for the issue:

```
import itertools
itertools
def test():
  global itertools
  itertools
test()
```

Forcing imports (or functions or variables) to be global allows read access. However, in Python `global` should only be needed for write access to global objects, not for read access.

**Comment by swallat** [comment]
@devhoffmann I think we should address this issue soon. I'll later take a look on this issue but might need some help.

**Comment by swallat** [comment]
I think I have fixed the issue. We still need to test it before we release it again. @nils1603 could you maybe test the projects again with this new version?
