### ISSUE TITLE
Can "Hal" be compiled on "CentOS"?

### ISSUE THREAD

**Issue by DaShaCHun123** [emsec/hal#469]
Hello, is there a more specific source code compilation method?
I want to compile on X86 or CentOS or arm systems，
Please give guidance。
![image](https://user-images.githubusercontent.com/105276615/183843914-3d49885b-8f70-451d-9a95-3f073f146215.png)

**Comment by nils1603** [comment]
Sadly we support only Ubuntu 20.04, as we don't have the time to maintain more Unix flavours.
