### ISSUE TITLE
Segmentation fault when creating new netlist from GUI

### ISSUE THREAD

**Issue by leongross** [emsec/hal#477]
**Describe the bug**
When creating a new netlist form the GUI, a segmentation fault occurs. 

**To Reproduce**
1. Open hal gui `./hal -g`
2. Press `Ctrl+n` to create a new netlist

**Expected behavior**
A new netlist creator should appear

**Desktop (please complete the following information):**
- Operating system: `Ubuntu 22.04`
- Kernel: `5.15.0-52-generic`
- HAL version: `8ef2442c2efa36afca51fbc9d9bf02a32d73d3c3`

**Error output in console:**
```
[20.10.2022 16:27:54] [gui] [info] Emergency dump of executed actions on signal 11
Segmentation fault (core dumped)
```

**Error output in system log (dmseg):**
```
[  241.987300] hal[1951]: segfault at fffffffffffffff8 ip 00007ff5ec722b26 sp 00007ffdf7893390 error 5 in hal_gui.so[7ff5ec5bd000+2b6000]
```

![hal](https://user-images.githubusercontent.com/64152526/196976839-3aa5cf80-de98-41bd-9f36-2371b1e0b062.png)

**Comment by RenWal** [comment]
Looks like the gate libraries aren't loaded before showing that dialog. I think this was introduced in c78aac094fa89cd953746a12e9f563bae5c89f7a in the process of moving to our new project manager and import system.

While we work on a full solution, I've prepared a hotfix in [branch fix/create-netlist-no-libraries](https://github.com/emsec/hal/tree/fix/create-netlist-no-libraries).

Looking at the code in [/plugins/gui/src/main_window/main_window.cpp#L581](https://github.com/emsec/hal/blob/master/plugins/gui/src/main_window/main_window.cpp#L581), it looks like this might need some additional work. Currently, this is using neither the User Action System nor the FileManager. @SJulianS @joern274 should we consider updating that method?

**Comment by RenWal** [comment]
Stumbled upon a few more things:

- netlists opened this way can't be closed (nothing happens)
- the "save" button is clickable but does nothing, the same goes for the keybind
- simulator temp files end up in the working directory (we call `ProjectManager::instance()->get_project_directory()` without checking whether a project is currently open, not sure if that is OK)
- the log isn't saved

We can probably simplify some stuff and get rid of those special cases if we enforce that a project is always created when we create a netlist – could be a temporary directory, or maybe even just immediately trigger a save dialog when creating a new netlist?

**Comment by joern274** [comment]
Please check whether issue has been fixed by now.

**Comment by RenWal** [comment]
Not crashing anymore, and I like the new dialog.

One minor thing, and certainly personal preference: Would it make sense to only allow the user to proceed after selecting a gate library? Right now, if you don't select one, you can still confirm the dialog and then you receive an error message.

**Comment by joern274** [comment]
Good point and easy to accomplish
