### ISSUE TITLE
Request - Python Function in HAL for Highlighting Logic Gates or Nets

### ISSUE THREAD

**Issue by CuriousCodeCrafter** [emsec/hal#537]
Hi,

I would like to know if there is any pre-implemented function in HAL capable of highlighting, in the Graph-View of the GUI, logic gates or nets. If not, it could be an interesting feature.

Best Regards.

**Comment by RenWal** [comment]
By "in HAL", do you mean via Python? All of the below also works using C++ though.

You can [modify the current selection](https://github.com/emsec/hal/wiki/Python-GUI-API) using the GUI API, which results in the selected gates and nets being highlighted.

You can also [create groupings](https://github.com/emsec/hal/wiki/Grouping) using the netlist API. A grouping is essentially an unsorted bin of gates and nets that can be assigned a color.

Does any of that suit your needs?
