### ISSUE TITLE
How to use functions in igraph quickly

### ISSUE THREAD

**Issue by ghyghy123** [emsec/hal#554]
Hello, I want to use Graph operators in igraph, as shown below, how can I call it quickly in Python command line?
![Snipaste_2024-01-26_11-21-25](https://github.com/emsec/hal/assets/58417169/097a7f3e-2bc4-4f20-8d0e-7772cd4e467a)

**Comment by RenWal** [comment]
I don't see what would be stopping you from just using the code from this example. (Assuming that this screenshot is showing [this manual page](https://python.igraph.org/en/stable/analysis.html#graph-operators) – please provide links to such sources) The HAL Python console is a fully-featured Python environment. Is this a question about HAL, or a Python question?

Would you mind providing some more information about the issue? What is your Python version? How did you install igraph? What have you tried already, and what exactly doesn't work? Is there any kind of specific error message?

**Comment by ghyghy123** [comment]
Thank you very much. The program I entered is as follows, and the error "AttributeError: module 'igraph' has no attribute 'Graph'", is it not installed? Or how do you install igraph?
![Snipaste_2024-01-26_20-48-05](https://github.com/emsec/hal/assets/58417169/1e895bcf-8c30-40fa-89be-3d28b24e8042)

**Comment by RenWal** [comment]
Huh … This looks like Python imports _something_, but not the _right_ thing. One thing that comes to my mind: Is there, by any chance, a folder called `igraph` in your working directory? And in general, which folder are you in when you start HAL, and what is the command you type in the command line to launch HAL?

**Comment by ghyghy123** [comment]
Hello, as shown below, there is a folder called igraph, I start hal in build folder with the command./bin/hal-g,
![Snipaste_2024-01-26_22-50-32](https://github.com/emsec/hal/assets/58417169/42d9b634-172a-4f55-8627-206438b53346)

**Comment by RenWal** [comment]
I guess Python is trying to import that folder as a module, which is not what we want.  
Try going up one folder, and then launching HAL as `./build/bin/hal -g`. See if that resolves the issue.

**Comment by ghyghy123** [comment]
Hello, I tried to start in the hal folder, using the command./build/bin/ hal-g, but it still seems to fail, is there any solution?
![Snipaste_2024-01-26_23-45-06](https://github.com/emsec/hal/assets/58417169/fdf9493f-920f-40c0-88de-0f92381fab1d)
![Snipaste_2024-01-26_23-48-32](https://github.com/emsec/hal/assets/58417169/e6f3ad4e-70a6-4f47-8795-694c9f62ec2c)

**Comment by RenWal** [comment]
Okay, we've solved one problem but there's another issue. I believe you did not install igraph for Python.

Since you have already found the igraph manual pages, please follow the [installation instructions](https://python.igraph.org/en/stable/install.html) there.

**Comment by ghyghy123** [comment]
Thank you very much, the igraph package problem was solved by installing it！！！
