### ISSUE TITLE
convert the netlist into a adjacency List or adjacency Matrix

### ISSUE THREAD

**Issue by ghyghy123** [emsec/hal#555]
Hello, in HAL, the netlist is regarded as a graph, the gate is regarded as a node, and the net is regarded as an edge. Is there any way to convert the netlist into a adjacency List or adjacency Matrix?Use the functions or plugins provided by the tool.

**Comment by RenWal** [comment]
Sure, you can do that in Python using any graph library you like (or even build that functionality yourself). I think the `igraph` Python module has built-in functions for generating adjacency lists and matrices.
There is no specific HAL feature for this.
