### ISSUE TITLE
Feature: Synchronize selection and color of modules in navigation and netlist

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#66]
It is currently hard to see which module color belongs to what name. I suggest the following additions:

- set the color of the module name in the navigation (or show a colored icon next to it) with the color of the module in the netlist graph.
- when clicking a module name in the navigation, highlight all gates in that module in the netlist graph.

**Comment by Slowpoke42** [comment]
I'm currently in the process of rewriting both the navigation and the graph view. The new versions will include these features :)
