### ISSUE TITLE
Feature: Allow manual selection of module colors

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#67]
HAL sometimes selects two colors very close to each other when creating many modules, making the different modules hard to see. I suggest a manual override for that color by:

- passing the color in the python command for creating a module
- right-clicking on a module in the navigation view

**Comment by Slowpoke42** [comment]
Part of the graph view rework in branch feature/new-graph-views

**Comment by swallat** [comment]
@Slowpoke42 Is this still Work in Progress?

**Comment by swallat** [comment]
Closed in favor of #195
