### ISSUE TITLE
Feature: Add option "show only this module" in graph view

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#86]
Suggestion for the dev working on the new graph view (if this is not already planned):

When working with large netlists where a functional unit (e.g. an FSM) is spread out across the entire graph, it is often hard to figure out how the components interact. I suggest adding a toggle "show only the selected module" that takes all gates and nets in the module (selected in the navigation list) and layouts them in a new, small graph.

This would allow for much easier visual inspection of the connections and you could increase the zoom level without something going off-screen.

**Comment by Slowpoke42** [comment]
Yup, already working on it. You can check out branch feature/new-graph-views if you want to take a look at it, but its obviously WIP code, meaning most of the components are not finished / connected, so dont expect to see much.

**Comment by swallat** [comment]
@Slowpoke42 Is this still Work in Progress?

**Comment by swallat** [comment]
Closed in favor of #195
