### ISSUE TITLE
Fix memory management in GUI

### ISSUE THREAD

**Issue by swallat** [emsec/hal#88]
Currently, when closing the GUI we get an error.  I think it has something to do with memory leaks from within the GUI. This also the problem for #7. We should make sure that we have correct memory management in the GUI following the Parent/Child paradigm.

**Comment by devhoffmann** [comment]
@swallat Any steps to reproduce this? I dont get any error

**Comment by swallat** [comment]
@devhoffmann Open the Gui -> Open a netlist -> Close the GUI -> Exit Code != 0. Thats what I mean by error.
