### ISSUE TITLE
netlist/module::set_name: does not check whether the passed name is the empty string

### ISSUE THREAD

**Issue by swallat** [emsec/hal#97]
netlist/module::set_name: does not check whether the passed name is the empty string. At the other hand, the create_module function (of the netlist) does not allow the empty string.

**Comment by swallat** [comment]
@devhoffmann Is this already fixed? (see your commit: 398f727553caa594e67c98448e2ee56b1b2975dc)

**Comment by devhoffmann** [comment]
Indeed already fixed.
